-- =============================================================================
-- PROPOSED (not applied) · Health data model 4/4
-- health_events (Timeline) · insights + insight_sources (What Changed, trend
-- summaries) · get_health_summary() (Me screen counts)
--
-- Both are DERIVED, server-written data that must always point back to
-- evidence:
--   * every timeline event links to a document and/or an encounter;
--   * every insight must have at least one insight_sources row — enforced at
--     COMMIT, so an ungrounded insight can never be saved.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- health_events — Timeline entries (rebuildable from documents/encounters).
-- -----------------------------------------------------------------------------
create type public.health_event_type as enum (
  'annual_check', 'consultation', 'blood_test', 'prescription', 'imaging', 'vaccination', 'procedure', 'other'
);

create table public.health_events (
  id                 uuid primary key default gen_random_uuid(),
  user_id            uuid not null references auth.users (id) on delete cascade,
  event_type         public.health_event_type not null,
  event_date         date not null,
  title              text not null check (char_length(title) between 1 and 200),
  summary            text check (summary is null or char_length(summary) <= 500),
  document_id        uuid,
  encounter_id       uuid,
  derivation_version text not null check (char_length(derivation_version) between 1 and 64),
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  constraint health_events_id_user_key unique (id, user_id),
  constraint health_events_document_fk foreign key (document_id, user_id)
    references public.documents (id, user_id) on delete cascade,
  constraint health_events_encounter_fk foreign key (encounter_id, user_id)
    references public.encounters (id, user_id),
  constraint health_events_has_source check (document_id is not null or encounter_id is not null)
);

create index health_events_user_date_idx on public.health_events (user_id, event_date desc);
create index health_events_document_idx on public.health_events (document_id);
create index health_events_encounter_idx on public.health_events (encounter_id);

create trigger health_events_set_updated_at
  before update on public.health_events
  for each row execute function private.set_updated_at();

alter table public.health_events enable row level security;
create policy "health_events_select_own" on public.health_events for select to authenticated
  using ((select auth.uid()) = user_id);
revoke all on public.health_events from anon, authenticated;
grant select on public.health_events to authenticated;

-- -----------------------------------------------------------------------------
-- insights — neutral, non-diagnostic statements derived from facts
-- ("HbA1c rose from 6.1 % to 6.5 %"). Generated by rules or AI; immutable;
-- regenerating = a new row that supersedes the old one.
-- -----------------------------------------------------------------------------
create type public.insight_type as enum ('value_change', 'new_medication', 'stopped_medication', 'new_condition', 'trend_summary');
create type public.insight_generator as enum ('rules', 'ai');
create type public.insight_source_role as enum ('current', 'previous', 'supporting');

create table public.insights (
  id                 uuid primary key default gen_random_uuid(),
  user_id            uuid not null references auth.users (id) on delete cascade,
  insight_type       public.insight_type not null,
  subject_display    text not null check (char_length(subject_display) between 1 and 200),
  title              text not null check (char_length(title) between 1 and 200),
  body_text          text not null check (char_length(body_text) between 1 and 1000),
  previous_value_text text check (previous_value_text is null or char_length(previous_value_text) <= 100),
  current_value_text text check (current_value_text is null or char_length(current_value_text) <= 100),
  unit               text check (unit is null or char_length(unit) <= 50),
  effective_date     date,
  compared_date      date,
  generated_by       public.insight_generator not null,
  generator_version  text not null check (char_length(generator_version) between 1 and 64),
  model_name         text check (model_name is null or char_length(model_name) <= 128),
  dismissed_at       timestamptz,
  supersedes_id      uuid,
  superseded_at      timestamptz,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  constraint insights_id_user_key unique (id, user_id),
  constraint insights_supersedes_fk foreign key (supersedes_id, user_id) references public.insights (id, user_id),
  constraint insights_ai_names_model check (generated_by <> 'ai' or model_name is not null)
);

create index insights_user_created_idx on public.insights (user_id, created_at desc);
create index insights_current_idx on public.insights (user_id, effective_date desc)
  where superseded_at is null and dismissed_at is null;

create trigger insights_set_updated_at
  before update on public.insights
  for each row execute function private.set_updated_at();

-- Immutable except dismissal (app) and supersession (server).
create or replace function private.insights_before_update()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (to_jsonb(new) - array['dismissed_at', 'superseded_at', 'updated_at'])
     is distinct from (to_jsonb(old) - array['dismissed_at', 'superseded_at', 'updated_at']) then
    raise exception 'insights are immutable — generate a new insight instead' using errcode = '42501';
  end if;
  if private.is_app_request() then
    if new.superseded_at is distinct from old.superseded_at then
      raise exception 'insights: only the server can supersede an insight' using errcode = '42501';
    end if;
    if old.dismissed_at is not null and new.dismissed_at is distinct from old.dismissed_at then
      raise exception 'insights: a dismissal cannot be undone from the app' using errcode = '22023';
    end if;
    if new.dismissed_at is not null then
      new.dismissed_at := now();
    end if;
  end if;
  return new;
end;
$$;

create trigger insights_before_update
  before update on public.insights
  for each row execute function private.insights_before_update();

-- -----------------------------------------------------------------------------
-- insight_sources — the evidence behind each insight (append-only).
-- Each row points at exactly one fact, or at a document/page.
-- -----------------------------------------------------------------------------
create table public.insight_sources (
  id               uuid primary key default gen_random_uuid(),
  user_id          uuid not null references auth.users (id) on delete cascade,
  insight_id       uuid not null,
  role             public.insight_source_role not null default 'supporting',
  observation_id   uuid,
  medication_id    uuid,
  condition_id     uuid,
  procedure_id     uuid,
  allergy_id       uuid,
  encounter_id     uuid,
  document_id      uuid,
  document_page_id uuid,
  created_at       timestamptz not null default now(),
  constraint insight_sources_insight_fk foreign key (insight_id, user_id)
    references public.insights (id, user_id) on delete cascade,
  constraint insight_sources_observation_fk foreign key (observation_id, user_id) references public.observations (id, user_id),
  constraint insight_sources_medication_fk  foreign key (medication_id, user_id)  references public.medications (id, user_id),
  constraint insight_sources_condition_fk   foreign key (condition_id, user_id)   references public.conditions (id, user_id),
  constraint insight_sources_procedure_fk   foreign key (procedure_id, user_id)   references public.procedures (id, user_id),
  constraint insight_sources_allergy_fk     foreign key (allergy_id, user_id)     references public.allergies (id, user_id),
  constraint insight_sources_encounter_fk   foreign key (encounter_id, user_id)   references public.encounters (id, user_id),
  constraint insight_sources_document_fk    foreign key (document_id, user_id)    references public.documents (id, user_id),
  constraint insight_sources_page_fk        foreign key (document_page_id, document_id) references public.document_pages (id, document_id),
  constraint insight_sources_one_fact check (
    num_nonnulls(observation_id, medication_id, condition_id, procedure_id, allergy_id, encounter_id) <= 1),
  constraint insight_sources_points_somewhere check (
    num_nonnulls(observation_id, medication_id, condition_id, procedure_id, allergy_id, encounter_id) = 1
    or document_id is not null),
  constraint insight_sources_page_needs_document check (document_page_id is null or document_id is not null)
);

create index insight_sources_insight_idx on public.insight_sources (insight_id);
create index insight_sources_observation_idx on public.insight_sources (observation_id) where observation_id is not null;
create index insight_sources_medication_idx on public.insight_sources (medication_id) where medication_id is not null;
create index insight_sources_user_idx on public.insight_sources (user_id);

create trigger insight_sources_append_only
  before update or delete on public.insight_sources
  for each row
  when (pg_trigger_depth() = 0)  -- allow cascades from account deletion
  execute function private.reject_change();

-- Grounding rule: checked at COMMIT so the insight and its sources can be
-- written in one transaction, but never an insight without sources.
create or replace function private.insights_require_evidence()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if exists (select 1 from public.insights i where i.id = new.id)
     and not exists (select 1 from public.insight_sources s where s.insight_id = new.id) then
    raise exception 'insights: every insight must cite at least one source' using errcode = '23514';
  end if;
  return null;
end;
$$;

create constraint trigger insights_require_evidence
  after insert on public.insights
  deferrable initially deferred
  for each row execute function private.insights_require_evidence();

create or replace function private.insights_after_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.supersedes_id is not null then
    update public.insights set superseded_at = now() where id = new.supersedes_id and superseded_at is null;
  end if;
  perform private.write_audit(new.user_id, 'insight.created', 'insights', new.id,
    jsonb_build_object('insight_type', new.insight_type, 'generated_by', new.generated_by,
                       'generator_version', new.generator_version, 'supersedes_id', new.supersedes_id));
  return null;
end;
$$;

create trigger insights_after_insert
  after insert on public.insights
  for each row execute function private.insights_after_insert();

alter table public.insights enable row level security;
alter table public.insight_sources enable row level security;

create policy "insights_select_own" on public.insights for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "insights_update_own" on public.insights for update to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "insight_sources_select_own" on public.insight_sources for select to authenticated
  using ((select auth.uid()) = user_id);

revoke all on public.insights, public.insight_sources from anon, authenticated;
grant select on public.insights, public.insight_sources to authenticated;
grant update (dismissed_at) on public.insights to authenticated;

create view public.current_insights with (security_invoker = true) as
  select * from public.insights where superseded_at is null and dismissed_at is null;
revoke all on public.current_insights from anon, authenticated;
grant select on public.current_insights to authenticated;

-- -----------------------------------------------------------------------------
-- get_health_summary() — the Me screen counts, computed under the caller's RLS.
-- -----------------------------------------------------------------------------
create or replace function public.get_health_summary()
returns table (record_count bigint, document_count bigint, active_medication_count bigint, last_updated timestamptz)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    (select count(*) from public.current_observations),
    (select count(*) from public.documents d where d.status <> 'pending_upload'),
    (select count(*) from public.current_medications m where m.status = 'active'),
    greatest(
      (select max(d.updated_at) from public.documents d),
      (select max(o.created_at) from public.observations o)
    );
$$;

revoke all on function public.get_health_summary() from public, anon;
grant execute on function public.get_health_summary() to authenticated;

revoke all on all functions in schema private from public, anon, authenticated;
